version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nextjs-dashboard-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextjs_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nextjs_dashboard"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Opcional: pgAdmin para visualizar o banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nextjs-dashboard-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - admin

volumes:
  postgres_data:
